"""
Books app views.
"""
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
from .models import Book
from .serializers import BookSerializer, BookListSerializer, BookCreateUpdateSerializer
from .filters import BookFilter
from .search import BookSearchFilter
from .ordering import CustomOrderingFilter
from .pagination import CustomPageNumberPagination
from apps.accounts.permissions import IsAdministratorOrReadOnly


class BookViewSet(viewsets.ModelViewSet):
    """
    Book Catalog API - Search, filter, and browse books
    
    Public: Browse books
    Admin: Full CRUD access
    """
    
    queryset = Book.objects.all()
    permission_classes = [IsAdministratorOrReadOnly]
    filter_backends = [BookSearchFilter, DjangoFilterBackend, CustomOrderingFilter]
    filterset_class = BookFilter
    search_fields = ['title', 'author', 'description', 'isbn', 'genre']
    ordering_fields = ['title', 'author', 'created_at', 'published_date']
    ordering = ['created_at']
    pagination_class = CustomPageNumberPagination

    def get_serializer_class(self):
        if self.action == 'list':
            return BookListSerializer
        if self.action in ['create', 'update', 'partial_update']:
            return BookCreateUpdateSerializer
        return BookSerializer
    
    @swagger_auto_schema(
        operation_summary="List all books",
        operation_description="Search, filter, sort, and paginate books",
        manual_parameters=[
            # Search FIRST
            openapi.Parameter(
                'search',
                openapi.IN_QUERY,
                description="Search books (fuzzy matching, handles typos)",
                type=openapi.TYPE_STRING,
                required=False,
            ),
            # Filters (auto-generated by DjangoFilterBackend, listed here for order control)
            openapi.Parameter(
                'title',
                openapi.IN_QUERY,
                description="(Optional) Filter by title",
                type=openapi.TYPE_STRING,
                required=False,
            ),
            openapi.Parameter(
                'author',
                openapi.IN_QUERY,
                description="(Optional) Filter by author",
                type=openapi.TYPE_STRING,
                required=False,
            ),
            openapi.Parameter(
                'genre',
                openapi.IN_QUERY,
                description="(Optional) Filter by genre",
                type=openapi.TYPE_STRING,
                required=False,
            ),
            openapi.Parameter(
                'isbn',
                openapi.IN_QUERY,
                description="(Optional) Filter by ISBN",
                type=openapi.TYPE_STRING,
                required=False,
            ),
            openapi.Parameter(
                'is_available',
                openapi.IN_QUERY,
                description="(Optional) Filter by availability",
                type=openapi.TYPE_BOOLEAN,
                required=False,
            ),
            openapi.Parameter(
                'published_year',
                openapi.IN_QUERY,
                description="(Optional) Filter by publication year",
                type=openapi.TYPE_INTEGER,
                required=False,
            ),
            # Sorting
            openapi.Parameter(
                'ordering',
                openapi.IN_QUERY,
                description="Sort results (default: asc)",
                type=openapi.TYPE_STRING,
                enum=['title_asc', 'title_desc', 'author_asc', 'author_desc', 'created_at_asc', 'created_at_desc', 'published_date_asc', 'published_date_desc'],
                required=False,
                default='created_at_asc',
            ),
            # Pagination
            openapi.Parameter(
                'page',
                openapi.IN_QUERY,
                description="Page number",
                type=openapi.TYPE_INTEGER,
                required=False,
                default=1,
            ),
            openapi.Parameter(
                'page_size',
                openapi.IN_QUERY,
                description="Items per page (max: 100)",
                type=openapi.TYPE_INTEGER,
                required=False,
                default=10,
            ),
        ],
        filter_inspectors=[],  # Disable auto-generation to control order
    )
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)
    
    def perform_create(self, serializer):
        """Create book and update search vector."""
        book = serializer.save()
        try:
            book.update_search_vector()
        except Exception:
            pass
    
    def perform_update(self, serializer):
        """Update book and refresh search vector."""
        book = serializer.save()
        try:
            book.update_search_vector()
        except Exception:
            pass
